language: python
python:
    - "3.5"
before_install:
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
    - pip install pytest pytest-cov
    - pip install coverage
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install ply
    - pip install aiohttp
    - pip install asynctest    
script:
    - py.test --cov timeseries --cov pype
    
after_success:
    - coveralls
